"""Convert raw hold STLs into web-ready GLBs for the editor.

Per mesh: decimate to TARGET_FACES, scale mm to m, center in XY, translate
so the wall-mount face (min Z) sits at z=0 with the hold protruding toward +Z.
This matches the flushBackFace convention in holdGeometry.ts.

Outputs GLBs to apps/web/public/models/holds/<type>/ plus holds-manifest.json
with per-variant real-world dimensions and attribution, consumed by the app.

Also generates holdModelConfig.generated.ts so the app's model registry cannot
drift from the shipped GLBs.

Usage: .venv/bin/python convert.py [--codegen-only]
"""

import json
import sys
from pathlib import Path

import fast_simplification
import numpy as np
import trimesh

HERE = Path(__file__).parent
RAW_DIR = HERE / "raw"
OUT_DIR = HERE / ".." / ".." / "apps" / "web" / "public" / "models" / "holds"

TARGET_FACES = 5000
MM_TO_M = 0.001


def convert(stl_path: Path, out_path: Path) -> dict:
    mesh = trimesh.load(stl_path, force="mesh")

    reduction = 1.0 - min(1.0, TARGET_FACES / len(mesh.faces))
    vertices, faces = fast_simplification.simplify(
        np.asarray(mesh.vertices, dtype=np.float32),
        np.asarray(mesh.faces, dtype=np.int64),
        target_reduction=reduction,
    )
    simplified = trimesh.Trimesh(vertices=vertices, faces=faces)
    simplified.merge_vertices()  # welds duplicated verts so normals shade smooth
    trimesh.repair.fix_normals(simplified)  # consistent outward winding, else faces get culled
    simplified.apply_scale(MM_TO_M)

    (min_corner, max_corner) = simplified.bounds
    center_x = (min_corner[0] + max_corner[0]) / 2
    center_y = (min_corner[1] + max_corner[1]) / 2
    simplified.apply_translation([-center_x, -center_y, -min_corner[2]])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # include_normals: without it the GLB ships no NORMAL attribute and
    # normal-dependent lights (hemisphere) render the mesh black
    simplified.export(out_path, include_normals=True)

    size = (simplified.bounds[1] - simplified.bounds[0]).tolist()
    return {
        "faces": int(len(simplified.faces)),
        "sizeMeters": [round(v, 4) for v in size],
        "fileBytes": out_path.stat().st_size,
    }


GENERATED_TS = (
    HERE / ".." / ".." / "apps" / "web" / "src" / "pages" / "editor"
    / "components" / "WallCanvas3D" / "config" / "holdModelConfig.generated.ts"
)


def merge_local_volumes(app_manifest: dict) -> None:
    """Volume GLBs come from volumes_blender.py (original assets), not
    Printables. Replaces the volume entry wholesale so reruns stay idempotent."""
    volumes_path = HERE / "volumes.json"
    if not volumes_path.exists():
        return
    app_manifest["holds"]["volume"] = json.loads(volumes_path.read_text())


def write_ts_config(app_manifest: dict) -> None:
    lines = [
        "/* AUTO-GENERATED by tools/holds/convert.py. Do not edit by hand. */",
        "import type { HoldType } from '@/stores/wallStore'",
        "",
        "export interface HoldModelVariant {",
        "  variant: string",
        "  path: string",
        "  /** Native bounding box in meters [x, y, z], back face at z=0 */",
        "  sizeMeters: [number, number, number]",
        "}",
        "",
        "export const holdModelVariants: Partial<Record<HoldType, HoldModelVariant[]>> = {",
    ]
    for hold_type, variants in sorted(app_manifest["holds"].items()):
        lines.append(f"  {hold_type}: [")
        for v in sorted(variants, key=lambda x: x["variant"]):
            size = ", ".join(str(s) for s in v["sizeMeters"])
            lines.append(
                f"    {{ variant: '{v['variant']}', path: '{v['path']}', sizeMeters: [{size}] }},"
            )
        lines.append("  ],")
    lines += ["}", ""]
    GENERATED_TS.write_text("\n".join(lines))
    print(f"wrote {GENERATED_TS.resolve()}")


def main() -> None:
    if "--codegen-only" in sys.argv:
        app_manifest = json.loads((OUT_DIR / "holds-manifest.json").read_text())
        merge_local_volumes(app_manifest)
        (OUT_DIR / "holds-manifest.json").write_text(
            json.dumps(app_manifest, indent=2, ensure_ascii=False)
        )
        write_ts_config(app_manifest)
        return

    manifest = json.loads((HERE / "manifest.json").read_text())
    app_manifest: dict = {"attribution": manifest["source"], "packs": manifest["packs"], "holds": {}}

    for entry in manifest["files"]:
        hold_type = entry["holdType"]
        stl_path = RAW_DIR / hold_type / entry["file"]
        if not stl_path.exists():
            print(f"missing {stl_path}, run download.py first")
            continue

        variant = entry["file"].removesuffix(".stl").lower()
        out_path = OUT_DIR / hold_type / f"{variant}.glb"
        stats = convert(stl_path, out_path)

        app_manifest["holds"].setdefault(hold_type, []).append(
            {
                "variant": variant,
                "path": f"/models/holds/{hold_type}/{variant}.glb",
                "pack": entry["printId"],
                **stats,
            }
        )
        print(
            f"{hold_type}/{variant}: {stats['faces']} faces, "
            f"{stats['sizeMeters']}, {stats['fileBytes'] / 1e3:.0f} KB"
        )

    merge_local_volumes(app_manifest)
    out = OUT_DIR / "holds-manifest.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(app_manifest, indent=2, ensure_ascii=False))
    print(f"wrote {out.resolve()}")
    write_ts_config(app_manifest)


if __name__ == "__main__":
    main()
