/* AUTO-GENERATED by tools/holds/convert.py. Do not edit by hand. */
import type { HoldType } from '@/stores/wallStore'

export interface HoldModelVariant {
  variant: string
  path: string
  /** Native bounding box in meters [x, y, z], back face at z=0 */
  sizeMeters: [number, number, number]
}

export const holdModelVariants: Partial<Record<HoldType, HoldModelVariant[]>> = {
  crimp: [
    { variant: 'bh_5x5_01', path: '/models/holds/crimp/bh_5x5_01.glb', sizeMeters: [0.051, 0.0403, 0.0393] },
    { variant: 'bh_5x5_09', path: '/models/holds/crimp/bh_5x5_09.glb', sizeMeters: [0.0525, 0.0512, 0.0481] },
    { variant: 'bh_5x5_17', path: '/models/holds/crimp/bh_5x5_17.glb', sizeMeters: [0.0378, 0.0454, 0.0486] },
    { variant: 'bh_5x5_25', path: '/models/holds/crimp/bh_5x5_25.glb', sizeMeters: [0.0454, 0.047, 0.0357] },
    { variant: 'bh_5x5_33', path: '/models/holds/crimp/bh_5x5_33.glb', sizeMeters: [0.0714, 0.052, 0.0465] },
    { variant: 'bh_5x5_41', path: '/models/holds/crimp/bh_5x5_41.glb', sizeMeters: [0.0481, 0.0667, 0.036] },
  ],
  jug: [
    { variant: 'ch1_xs', path: '/models/holds/jug/ch1_xs.glb', sizeMeters: [0.0663, 0.0525, 0.0294] },
    { variant: 'ch2_xs', path: '/models/holds/jug/ch2_xs.glb', sizeMeters: [0.077, 0.0523, 0.0319] },
    { variant: 'ch3_xs', path: '/models/holds/jug/ch3_xs.glb', sizeMeters: [0.0911, 0.0442, 0.0321] },
    { variant: 'ch4_xs', path: '/models/holds/jug/ch4_xs.glb', sizeMeters: [0.077, 0.0764, 0.0377] },
  ],
  pinch: [
    { variant: 'bh_10x5_03', path: '/models/holds/pinch/bh_10x5_03.glb', sizeMeters: [0.102, 0.0538, 0.0366] },
    { variant: 'bh_10x5_12', path: '/models/holds/pinch/bh_10x5_12.glb', sizeMeters: [0.0975, 0.0572, 0.0306] },
    { variant: 'bh_10x5_21', path: '/models/holds/pinch/bh_10x5_21.glb', sizeMeters: [0.0989, 0.0527, 0.0354] },
    { variant: 'bh_10x5_30', path: '/models/holds/pinch/bh_10x5_30.glb', sizeMeters: [0.1055, 0.0377, 0.029] },
  ],
  pocket: [
    { variant: 'fh1_1', path: '/models/holds/pocket/fh1_1.glb', sizeMeters: [0.1374, 0.1375, 0.0459] },
    { variant: 'fh2_1', path: '/models/holds/pocket/fh2_1.glb', sizeMeters: [0.1352, 0.1353, 0.063] },
    { variant: 'fh3_1', path: '/models/holds/pocket/fh3_1.glb', sizeMeters: [0.1828, 0.1406, 0.0654] },
    { variant: 'fh4_1', path: '/models/holds/pocket/fh4_1.glb', sizeMeters: [0.1909, 0.1415, 0.0518] },
  ],
  sloper: [
    { variant: 'rockhold_t1_04', path: '/models/holds/sloper/rockhold_t1_04.glb', sizeMeters: [0.0847, 0.1491, 0.033] },
    { variant: 'rockhold_t2_04', path: '/models/holds/sloper/rockhold_t2_04.glb', sizeMeters: [0.0553, 0.1093, 0.0349] },
    { variant: 'rockhold_t2_06', path: '/models/holds/sloper/rockhold_t2_06.glb', sizeMeters: [0.0945, 0.0665, 0.0339] },
    { variant: 'rockhold_t3_06', path: '/models/holds/sloper/rockhold_t3_06.glb', sizeMeters: [0.1464, 0.0738, 0.0287] },
  ],
  volume: [
    { variant: 'vol_box', path: '/models/holds/volume/vol_box.glb', sizeMeters: [0.62, 0.62, 0.2] },
    { variant: 'vol_rail_long', path: '/models/holds/volume/vol_rail_long.glb', sizeMeters: [0.34, 1.15, 0.17] },
    { variant: 'vol_ramp', path: '/models/holds/volume/vol_ramp.glb', sizeMeters: [0.36, 1.0, 0.24] },
    { variant: 'vol_tetra_ridge', path: '/models/holds/volume/vol_tetra_ridge.glb', sizeMeters: [0.84, 0.64, 0.18] },
    { variant: 'vol_tetra_squat', path: '/models/holds/volume/vol_tetra_squat.glb', sizeMeters: [0.6, 0.56, 0.28] },
    { variant: 'vol_tetra_tall', path: '/models/holds/volume/vol_tetra_tall.glb', sizeMeters: [0.32, 0.84, 0.22] },
  ],
}
